name: Build Flutter APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Extract Project Files
        run: |
          unzip -o Lawyer_App_V2_Flu*.zip
          TARGET_DIR=$(find . -name "pubspec.yaml" -exec dirname {} \;)
          echo "PROJECT_DIR=$TARGET_DIR" >> $GITHUB_ENV

      - name: Recreate Clean Android Folder
        run: |
          cd ${{ env.PROJECT_DIR }}
          # حذف مجلد الأندرويد القديم المسبب للمشاكل وإنشاء واحد جديد متوافق
          rm -rf android
          flutter create . --platforms=android

      - name: Install Dependencies
        run: |
          cd ${{ env.PROJECT_DIR }}
          flutter pub get

      - name: Build APK
        run: |
          cd ${{ env.PROJECT_DIR }}
          flutter build apk --release
