name: Build Flutter APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Extract Project Files
        run: |
          unzip -o Lawyer_App_V2_Flu*.zip
          TARGET_DIR=$(find . -name "pubspec.yaml" -exec dirname {} \;)
          echo "PROJECT_DIR=$TARGET_DIR" >> $GITHUB_ENV

      - name: Fix Android v1 Embedding
        run: |
          cd ${{ env.PROJECT_DIR }}
          # تعديل ملف المنفست برمجياً لإجبار النظام على قبول البنية الحديثة
          MANIFEST_FILE=$(find . -name "AndroidManifest.xml" | head -n 1)
          if [ -f "$MANIFEST_FILE" ]; then
            sed -i '/<meta-data/d' "$MANIFEST_FILE"
          fi

      - name: Install Dependencies
        run: |
          cd ${{ env.PROJECT_DIR }}
          flutter pub get

      - name: Build APK
        run: |
          cd ${{ env.PROJECT_DIR }}
          flutter build apk --release

      - name: Upload APK Result
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: |
            **/build/app/outputs/flutter-apk/app-release.apk
            **/build/app/outputs/apk/release/app-release.apk
